const textData = [
    "Believe in yourself.",
    "Stay positive always.",
    "You are amazing!",
    "Keep going, never quit.",
    "Smile, it's contagious.",
    "Dream big, work hard.",
    "Embrace the journey.",
    "Find joy daily.",
    "Be kind always.",
    "Laugh out loud.",
    "You got this!",
    "Never give up.",
    "Make today count.",
    "Choose happiness.",
    "Live, laugh, love.",
    "Be your own sunshine.",
    "Create your own magic.",
    "Inspire and be inspired.",
    "Shine bright today.",
    "Positive vibes only.",
    "Adventure awaits you.",
    "Seize the moment.",
    "Good things happen.",
    "Stay humble, hustle hard.",
    "Progress, not perfection.",
    "You are enough.",
    "Focus on the good.",
    "Enjoy the little things.",
    "Be fearless, be bold.",
    "Success is coming.",
    "Work hard, stay humble.",
    "Today is your day.",
    "Make it happen.",
    "Believe you can.",
    "Chase your dreams.",
    "Be a rainbow.",
    "Spread kindness.",
    "You're doing great.",
    "Never stop learning.",
    "Stay curious always.",
    "Be the change.",
    "Love yourself first.",
    "Take a deep breath.",
    "Everything will be okay.",
    "Find your strength.",
    "Challenge yourself daily.",
    "Growth is constant.",
    "Be present now.",
    "You are powerful.",
    "Trust your journey.",
    "New day, new start.",
    "Make memories today.",
    "Live without regrets.",
    "Be uniquely you.",
    "Your potential is limitless.",
    "Stay wild, moon child.",
    "Collect moments, not things.",
    "Do what you love.",
    "Love what you do.",
    "Keep shining bright.",
    "You're a star!",
    "Don't stop believing.",
    "Magic is real.",
    "Choose joy always.",
    "Be a light.",
    "Radiate positivity.",
    "Good vibes only.",
    "Happy thoughts.",
    "Live fully now.",
    "Dream without fear.",
    "Love without limits.",
    "Be patient, be kind.",
    "You are capable.",
    "Stay true to you.",
    "Make a difference.",
    "Inspire others.",
    "Be grateful daily.",
    "Count your blessings.",
    "Today is a gift.",
    "Embrace your flaws.",
    "You are worthy.",
    "Find your purpose.",
    "Never look back.",
    "Forward always.",
    "Keep moving forward.",
    "One step at a time.",
    "You're a legend.",
    "Stay awesome!",
    "Be happy now.",
    "Live your best life.",
    "Create your destiny.",
    "Be the exception.",
    "Your time is now.",
    "Make waves.",
    "Be unforgettable.",
    "Shine your light.",
    "You're a masterpiece.",
    "Stay golden.",
    "Be a warrior.",
    "Conquer today.",
    "You're incredible!",
    "Never settle.",
    "Aim high.",
    "Reach for stars.",
    "Be bold, be brave."
];

export default textData;    