const  data = [
  {
    name: "CSK",
    fullName: "Chennai Super Kings",
    lastTitleYear: 2023,
    totalTitles: 5,
    captain: "MS Dhoni",
    state: "Tamil Nadu",
    primaryColour: "#FFFF3C",
    secondaryColour: "#0081E9",
  },
  {
    name: "MI",
    fullName: "Mumbai Indians",
    lastTitleYear: 2020,
    totalTitles: 5,
    captain: "Rohit Sharma",
    state: "Maharashtra",
    primaryColour: "#004BA0",
    secondaryColour: "#D1AB3E",
  },
  {
    name: "KKR",
    fullName: "Kolkata Knight Riders",
    lastTitleYear: 2024,
    totalTitles: 3,
    captain: "Shreyas Iyer",
    state: "West Bengal",
    primaryColour: "#3A225D",
    secondaryColour: "#F7D54E",
  },
  {
    name: "RR",
    fullName: "Rajasthan Royals",
    lastTitleYear: 2008,
    totalTitles: 1,
    captain: "Shane Warne",
    state: "Rajasthan",
    primaryColour: "#FF1493",
    secondaryColour: "#00ADEF",
  },
  {
    name: "SRH",
    fullName: "Sunrisers Hyderabad",
    lastTitleYear: 2016,
    totalTitles: 1,
    captain: "David Warner",
    state: "Telangana",
    primaryColour: "#FF6600",
    secondaryColour: "#000000",
  },
  {
    name: "GT",
    fullName: "Gujarat Titans",
    lastTitleYear: 2022,
    totalTitles: 1,
    captain: "Hardik Pandya",
    state: "Gujarat",
    primaryColour: "#1B2133",
    secondaryColour: "#DBBE6E",
  },
  {
    name: "RCB",
    fullName: "Royal Challengers Bengaluru",
    lastTitleYear: 2025,
    totalTitles: 1,
    captain: "Rajat Patidar",
    state: "Karnataka",
    primaryColour: "#FF0000",
    secondaryColour: "#000000",
  },
];
export default data;
